ALTER TABLE customers
ADD COLUMN username VARCHAR(255) UNIQUE NOT NULL DEFAULT '',
ADD COLUMN password VARCHAR(255) NOT NULL DEFAULT '';

ALTER TABLE customers
ALTER COLUMN username DROP DEFAULT,
ALTER COLUMN password DROP DEFAULT;